### ISSUE TITLE
问一下， 这个怎么用？

### ISSUE THREAD

**Issue by khjde1207** [mengzhe1973/react-native-videoview#1]
"react-native": "0.56.0"

react-native init asdf 
cd asdf 
npm install --s react-native-videoview
react-native link react-native-videoview 

以后就出问题了。 

还需要做什么吗？

**Comment by khjde1207** [comment]
![image](https://user-images.githubusercontent.com/18232924/44790847-3af32180-abdb-11e8-8f86-c8c2940cee39.png)

**Comment by khjde1207** [comment]
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"type":"InternalError","errors":[],"message":"Metro Bundler has encountered an internal error, please check your terminal error output for more details"}
processBundleResult
    BundleDownloader.java:285
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:163
execute
    RealCall.java:153
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1167
run
    ThreadPoolExecutor.java:641
run
    Thread.java:764

**Comment by khjde1207** [comment]
oading dependency graph...(node:5192) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /home/khjde1207/projects/201807/reactnative/asdf/node_modules/react-native-videoview/node_modules/react-native/package.json collides with /home/khjde1207/projects/201807/reactnative/asdf/node_modules/react-native/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/home/khjde1207/projects/201807/reactnative/asdf/node_modules/jest-haste-map/build/index.js:446:17)
    at workerReply (/home/khjde1207/projects/201807/reactnative/asdf/node_modules/jest-haste-map/build/index.js:496:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error: bundling failed: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /home/khjde1207/projects/201807/reactnative/asdf/node_modules/react-native-videoview/node_modules/react-native/package.json collides with /home/khjde1207/projects/201807/reactnative/asdf/node_modules/react-native/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/home/khjde1207/projects/201807/reactnative/asdf/node_modules/jest-haste-map/build/index.js:446:17)
    at workerReply (/home/khjde1207/projects/201807/reactnative/asdf/node_modules/jest-haste-map/build/index.js:496:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

**Comment by mengzhe1973** [comment]
可能是这个插件里的一些依赖没有引进来，这个插件只能适用于android的。

**Comment by mengzhe1973** [comment]
试试这个https://github.com/react-native-community/react-native-video

**Comment by khjde1207** [comment]
谢谢答复。
那个插件我已经试过。 
用Android VideoView 可以播放的，用那个插件就不行。所以找到这里了。

**Comment by mengzhe1973** [comment]
我这个插件是演示怎么写插件写了一个样例，可能有一些问题，不过我写的demo引进来的可以播放了，演示也没问题。后续我在试验一下完善完善，对了，你的名字是韩文，给我邮箱发的信也是韩文写的。但是你写回复用的中文。你不是韩国的吧。

**Comment by khjde1207** [comment]
你好。 
我做了一个VideoView把问题解决了。 
我是韩国人哦。会一些汉语。

**Comment by mengzhe1973** [comment]
you are so good！
